### ISSUE TITLE
Possibility of not publishing changes until approved by an administrator

### ISSUE THREAD

**Issue by ghost** [MissVeronica/um-profile-content-moderation#3]
Hello,

I would like an e-mail to be sent to the administration e-mail address as soon as a user modifies his profile. But that the changes are not published until an administrator approves them. However, I would like the user's profile to remain visible during this short period of time, but with the old information.

Is it possible for you to integrate this feature into your plugin? Or is it already possible?

I don't know if I've made myself clear? I'm at your disposal if you need any further information on my request.

PS: I love your plugin, which integrates perfectly with Ultimate Member !!!! Thank you for your generous work.

Have a nice day and thanks in advance,
Alexis Grolot

**Comment by MissVeronica** [comment]
Yes this enhancement with a delayed update was planned from the beginning but setting the account to Admin review was easier to implement.
In coding it's similar to the Rollback feature and will probably be an update in the future.

**Comment by ghost** [comment]
Great, I can't wait for you to release this update so I can use the delayed update enhancement on my WordPress site. 

I hope you can get it out as soon as possible!

**Comment by ghost** [comment]
Hello,

I would like to know when this improvement will be available as it is for a customer's site.
And it's quite urgent.

Bravo in any case for all your work, this plugin really helps me a lot!

Have a nice day,
Alexis Grolot

**Comment by MissVeronica** [comment]
Hello,
Most of the coding for the delayed update is ready only a few backend performance improvements are still required and another procedure for checking when an update is available for download.
Testing takes longer time than my other plugin "Happy Birthday", which I work with also and make similar coding improvements in both plugins.

**Comment by ghost** [comment]
Great, I can't wait for this update to be released.

**Comment by MissVeronica** [comment]
Now you can read a first text proposal of the new plugin update "UM Profile Content Moderation next update 3.6.0"

**Comment by MissVeronica** [comment]
Version 3.6.0 ready for download now.

**Comment by ghost** [comment]
Thank you once again for all your fabulous work!

I downloaded version 3.6.0, but am I the only one without access to the settings?
![Capture d'écran 2024-08-08 152039](https://github.com/user-attachments/assets/59b92555-325f-46af-bf3b-396fa72b6e23)

**Comment by MissVeronica** [comment]
There might be an issue when Content Moderation is the first sub item, at my test site it's the 3rd sub item.
I will try to reconfigure my extensions to see if there is another setup for the first extension.

**Comment by MissVeronica** [comment]
You can try to install the free UM extension Online which will take first position.
https://wordpress.org/plugins/um-online/

**Comment by MissVeronica** [comment]
I have made a fix for this issue and version 3.6.1 will soon be available for download

**Comment by MissVeronica** [comment]
Version 3.6.1 ready for download now. 
Will fix this issue when the plugin is the first UM Extension

**Comment by ghost** [comment]
I've downloaded version 3.6.1, which works perfectly and fixes the problem when this plugin is the first Ultimate Member extension.

I was able to set it up properly to enable delayed profile updates, and it's just what I needed.

Thank you very much for your work on this plugin and I wish you all the best for the future.

Alexis Grolot
